permalink: /:year/:month/:day/:title/
url: http:nightest.github.com
author: Eugene
pygments: true
safe: false
paginate: 16
auto: true
#markdown: kramdown
#kramdown:
#    input: GFM
#    syntax_highlighter: rouge
markdown: redcarpet
redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]


