permalink: /:year/:month/:day/:title/
url: http:nightest.github.com
author: Eugene
pygments: true
safe: false
paginate: 16
auto: true
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge


